sudo: required
services:
  - docker

before_install:
  - docker build -t murugun9/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run murugun9/react-test npm run test -- --coverage

after_success:
  - docker build -t murugun9/multi-client ./client
  - docker build -t murugun9/multi-nginx ./nginx
  - docker build -t murugun9/multi-server ./server
  - docker build -t murugun9/multi-worker ./worker
  #Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  #Take those images and push to docker hub
  - docker push murugun9/multi-client
  - docker push murugun9/multi-nginx
  - docker push murugun9/multi-server
  - docker push murugun9/multi-worker
